events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location /game-assets/ {
            proxy_pass http://storage:9000/game-assets/;
            proxy_set_header Host $host;
        }

        location /file/ {
            proxy_pass http://storage:9000/file/;
            proxy_set_header Host $host;
        }

        # Xử lý file .js.br
        location ~* /game-assets/.*\.js\.br$ {
            proxy_pass http://storage:9000;
            proxy_set_header Host $host;
            
            # 1. Xóa header Content-Type cũ từ MinIO
            proxy_hide_header Content-Type; 
            
            # 2. Thêm header mới chuẩn
            add_header Content-Type application/javascript;
            add_header Content-Encoding br;
        }

        # Xử lý file .wasm.br
        location ~* /game-assets/.*\.wasm\.br$ {
            proxy_pass http://storage:9000;
            proxy_set_header Host $host;
            
            proxy_hide_header Content-Type;
            add_header Content-Type application/wasm;
            add_header Content-Encoding br;
        }

        # Xử lý file .data.br
        location ~* /game-assets/.*\.data\.br$ {
            proxy_pass http://storage:9000;
            proxy_set_header Host $host;
            
            proxy_hide_header Content-Type;
            add_header Content-Type application/octet-stream;
            add_header Content-Encoding br;
        }
    }
}